# Generated by Django 4.0.1 on 2022-02-08 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=64, verbose_name='연락 수단')),
                ('concern', models.CharField(max_length=64, verbose_name='관심 보험')),
                ('price', models.CharField(max_length=64, verbose_name='월 보험료')),
                ('hospital', models.CharField(max_length=64, verbose_name='병원 이력')),
                ('hospitalTreatment', models.CharField(max_length=64, verbose_name='의료 행위')),
                ('hospitalDisease', models.CharField(max_length=64, verbose_name='증상 병명')),
                ('disease', models.CharField(max_length=64, verbose_name='지병')),
                ('familyDisease', models.CharField(max_length=64, verbose_name='가족력')),
                ('familyDiseaseEtc', models.CharField(max_length=64, verbose_name='가족력 기타')),
                ('birth', models.CharField(max_length=64, verbose_name='생년월일')),
                ('gender', models.CharField(max_length=64, verbose_name='성별')),
                ('job', models.CharField(max_length=64, verbose_name='직업')),
                ('region', models.CharField(max_length=64, verbose_name='거주지')),
                ('userIP', models.ForeignKey(db_column='userIP', on_delete=django.db.models.deletion.CASCADE, to='home.home', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '비교견적',
                'verbose_name_plural': '비교견적',
                'db_table': 'gauser_compare',
            },
        ),
    ]
