# Generated by Django 4.0.1 on 2022-02-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gauser', '0002_compare_contact_alter_compare_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='userIP',
        ),
    ]
