# Generated by Django 4.0.1 on 2022-02-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauser', '0003_remove_compare_userip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myinsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='연락처')),
                ('consultingDate', models.CharField(blank=True, max_length=64, null=True, verbose_name='상담날짜')),
                ('consultingTime', models.CharField(blank=True, max_length=64, null=True, verbose_name='상담시간')),
            ],
        ),
    ]
