# Generated by Django 4.0.1 on 2022-02-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gauser', '0004_myinsurance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myinsurance',
            options={'verbose_name': '내보험', 'verbose_name_plural': '내보험'},
        ),
        migrations.AlterModelTable(
            name='myinsurance',
            table='gauser_myinsurance',
        ),
    ]
