# Generated by Django 4.0.1 on 2022-02-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauser', '0005_alter_myinsurance_options_alter_myinsurance_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='userIP',
            field=models.CharField(default='유저IP', max_length=64, verbose_name='유저IP'),
        ),
        migrations.AddField(
            model_name='myinsurance',
            name='userIP',
            field=models.CharField(default='유저IP', max_length=64, verbose_name='유저IP'),
        ),
    ]
