# Generated by Django 4.0.1 on 2022-03-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauser', '0006_compare_userip_myinsurance_userip'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='registerDate',
            field=models.CharField(default='0', max_length=64, verbose_name='등록시간'),
        ),
        migrations.AddField(
            model_name='myinsurance',
            name='registerDate',
            field=models.CharField(default='0', max_length=64, verbose_name='등록시간'),
        ),
    ]
