# Generated by Django 4.0.1 on 2022-07-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauser', '0007_compare_registerdate_myinsurance_registerdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIP', models.CharField(default='유저IP', max_length=64, verbose_name='유저IP')),
                ('registerDate', models.CharField(default='0', max_length=64, verbose_name='등록시간')),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='연락처')),
                ('consultingDate', models.CharField(blank=True, max_length=64, null=True, verbose_name='상담날짜')),
                ('consultingTime', models.CharField(blank=True, max_length=64, null=True, verbose_name='상담시간')),
            ],
            options={
                'verbose_name': '상담예약',
                'verbose_name_plural': '상담예약',
                'db_table': 'gauser_consulting',
            },
        ),
    ]
