# Generated by Django 4.0.1 on 2022-07-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauser', '0008_consulting'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='selectType',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='연락수단'),
        ),
    ]
