# Generated by Django 4.0.1 on 2022-02-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIP', models.CharField(max_length=64, verbose_name='유저IP')),
                ('refreshCount', models.IntegerField(verbose_name='홈페이지 새로고침')),
                ('compareCount', models.IntegerField(verbose_name='보험견적비교')),
                ('diagnosisCount', models.IntegerField(verbose_name='My보험 진단')),
            ],
            options={
                'verbose_name': '홈페이지 버튼 횟수',
                'verbose_name_plural': '홈페이지 버튼 횟수',
                'db_table': 'home_homeButton',
            },
        ),
    ]
