# Generated by Django 4.0.1 on 2022-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_comparecount_alter_home_diagnosiscount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': '버튼 횟수', 'verbose_name_plural': '버튼 횟수'},
        ),
        migrations.AddField(
            model_name='home',
            name='birthCount',
            field=models.IntegerField(default='0', verbose_name='My보험 진단'),
        ),
        migrations.AddField(
            model_name='home',
            name='concernCount',
            field=models.IntegerField(default='0', verbose_name='My보험 진단'),
        ),
        migrations.AddField(
            model_name='home',
            name='familyDiseaseCount',
            field=models.IntegerField(default='0', verbose_name='My보험 진단'),
        ),
        migrations.AddField(
            model_name='home',
            name='hospitalCount',
            field=models.IntegerField(default='0', verbose_name='My보험 진단'),
        ),
        migrations.AddField(
            model_name='home',
            name='methodCount',
            field=models.IntegerField(default='0', verbose_name='My보험 진단'),
        ),
        migrations.AddField(
            model_name='home',
            name='priceCount',
            field=models.IntegerField(default='0', verbose_name='My보험 진단'),
        ),
        migrations.AddField(
            model_name='home',
            name='startCount',
            field=models.IntegerField(default='0', verbose_name='My보험 진단'),
        ),
    ]
