# Generated by Django 4.0.1 on 2022-02-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_home_options_home_birthcount_home_concerncount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='birthCount',
            field=models.IntegerField(default='0', verbose_name='개인정보'),
        ),
        migrations.AlterField(
            model_name='home',
            name='concernCount',
            field=models.IntegerField(default='0', verbose_name='관심보험'),
        ),
        migrations.AlterField(
            model_name='home',
            name='familyDiseaseCount',
            field=models.IntegerField(default='0', verbose_name='가족력'),
        ),
        migrations.AlterField(
            model_name='home',
            name='hospitalCount',
            field=models.IntegerField(default='0', verbose_name='병원이력'),
        ),
        migrations.AlterField(
            model_name='home',
            name='methodCount',
            field=models.IntegerField(default='0', verbose_name='연락수단'),
        ),
        migrations.AlterField(
            model_name='home',
            name='priceCount',
            field=models.IntegerField(default='0', verbose_name='월 보험료'),
        ),
        migrations.AlterField(
            model_name='home',
            name='refreshCount',
            field=models.IntegerField(default='1', verbose_name='홈페이지 새로고침'),
        ),
        migrations.AlterField(
            model_name='home',
            name='startCount',
            field=models.IntegerField(default='0', verbose_name='비교견적 시작'),
        ),
    ]
