# Generated by Django 4.0.1 on 2022-02-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_home_birthcount_alter_home_concerncount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='time',
            field=models.IntegerField(default='0', verbose_name='홈페이지 채류시간'),
        ),
    ]
