# Generated by Django 4.0.1 on 2022-02-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_home_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='time',
            new_name='stayTime',
        ),
    ]
