# Generated by Django 4.0.1 on 2022-03-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_time_home_staytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='registerDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록시간'),
        ),
    ]
