# Generated by Django 4.0.1 on 2022-03-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_home_registerdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='registerDate',
            field=models.CharField(default='0', max_length=64, verbose_name='등록시간'),
        ),
    ]
