# Generated by Django 4.0.1 on 2022-05-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_home_registerdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='stayTime',
            field=models.FloatField(default='0', verbose_name='홈페이지 채류시간'),
        ),
    ]
