# Generated by Django 4.0.1 on 2022-05-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_home_staytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIP', models.GenericIPAddressField(null=True, verbose_name='유저IP')),
            ],
            options={
                'verbose_name': '아이피',
                'verbose_name_plural': '아이피',
                'db_table': 'home_userIP',
            },
        ),
    ]
