# Generated by Django 4.0.1 on 2022-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCount', models.IntegerField(default='0', verbose_name='방문자수')),
            ],
            options={
                'verbose_name': '방문자수',
                'verbose_name_plural': '방문자수',
                'db_table': 'home_userCount',
            },
        ),
        migrations.DeleteModel(
            name='UserIP',
        ),
    ]
