# Generated by Django 4.0.1 on 2022-06-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_usercount_delete_userip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='diagnosisCount',
            field=models.IntegerField(default='0', verbose_name='보험견적비교2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='refreshCount',
            field=models.IntegerField(default='0', verbose_name='홈페이지 새로고침'),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='userCount',
            field=models.IntegerField(verbose_name='방문자수'),
        ),
    ]
