# Generated by Django 4.0.1 on 2022-06-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_home_diagnosiscount_alter_home_refreshcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='stayTime2',
            field=models.FloatField(default='0', verbose_name='홈페이지 채류시간2'),
        ),
    ]
