# Generated by Django 4.0.1 on 2022-07-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_home_staytime2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='stayTime2',
        ),
    ]
