# Generated by Django 4.0.1 on 2022-07-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_home_staytime2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Post ID'),
        ),
    ]
